name: coast
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.6    # Python version 3.8
  - compilers
  - llvm-openmp
  - scikit-learn==0.21.2  # Machine learning library
  - sphinx
  - importlib_resources
  - pip           # Python package
  - pandas        # Labeled array library
  - netCDF4       # Wrapper for netcdf4
  - xarray        # N-d labeled array library
  - matplotlib    # 2D plotting library
  - numpy         # N-d array and numerics
  - scipy         # Common math/stats/science functions
  - scikit-image  # Image processing routines
  - geopandas     # Labeled array library for geosciences
  - shapely       # Geometric library
  - cftime        # Time units decoder
  - cartopy       # Geographic plotting toolkit
  - myst-nb       # Notebook syntax
  - sympy         # Symbolic expression
  - cmocean       # Colormaps for oceanography
  - jupyterlab    # Jupyter Lab environment
  - jupyter-book  # Jupyter book environment
  - basemap       # Mapping package
  - h5py          # Wrapper for HDF5
  - pymannkendall # Mann-Kendall trend analysis
  - seaborn       # Statistical visualizations
  - pyresample    # Geographic resampling tools
  - statsmodels   # Regression/modeling toolkit
  - wget
  - pip:
    - pyproj      # Geographic projections
    - radwave
    - wavespectra
